package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    check(archived == false) {
        "Unexpected archived: '$archived'"
    }
    archived = true

    features {
        add {
            feature {
                type = "JetBrains.SharedResources"
                id = "PROJECT_EXT_24"
                param("values", "testValue")
                param("name", "TestRes")
                param("type", "custom")
            }
        }
    }
}
